// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apvwjmhseqbuxmjrqcfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdndqbWhzZXFidXhtanJxY2ZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzMTA5NzAsImV4cCI6MjA1MDg4Njk3MH0.rrNVwHLbnsXznjG7TQ9W1lTY6AAR09iUe-rAoDf6XKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);